### ISSUE TITLE
Create controller for the user's endpoints

### ISSUE THREAD

**Issue by dritoferro** [codenation-dev/squad-6-ad-nodejs-kroton-1#7]
# Routes

- [x] Login
- [x] User CRUD

**Comment by talisonmaturana** [comment]
Hello guys. About the routes, for login I've already created this route, is the session controller, because when we log in an application we create a session.

**Comment by dritoferro** [comment]
> Hello guys. About the routes, for login I've already created this route, is the session controller, because when we log in an application we create a session.

Hey man! 
I'm in doubt...I read on the guide that we need to receive a token with every request... and if we use session will we still receive a token ?Also... is session makes sense for REST APIs?

**Comment by talisonmaturana** [comment]
Yes, is possible to receive a token because the token is saved in session if it is not expired. So if you are authenticated, you'll have a token and will use it for the requests, some routes will be available only for authenticated users. 
Like we have in codenation dashboard, is only one token.

![image](https://user-images.githubusercontent.com/11711562/75681934-55480880-5c73-11ea-89af-4cf346669a44.png)
